### ISSUE TITLE
Missing gff2zff.pl script

### ISSUE THREAD

**Issue by kastman** [KorfLab/SNAP#1]
Hi @iankorf,

I'm trying to implement the AGAPE Yeast annotation pipeline in our lab, and am finding some inconsistencies. One that you may be able to help me with is a script called **`gff2zff.pl`**, used with a `-sp <name>` flag, from here:

https://github.com/yeastgenome/AGAPE/blob/9825c208853a696631c93fcfe6b041e16cf7db0f/prep_maker.sh#L20

It seems that script was distributed within SNAP (I also found a [reference](https://www.biostars.org/p/148966/) on biostars saying that script was "from the author", but I can't find it in any of the releases on gitlab or from the lab site. I found `SNAP/gff3_to_zff.pl` in this repo, but I don't think it tkaes the `-sp` flag, so I suspect it's not doing exactly what the AGAPE authors intended; I'm going to try it and see. In the meantime, would you mind pointing me in the right direction?

Thanks,

**Comment by iankorf** [comment]
SNAP has been distributed with a gff converter with different names at different times. It's a very simple script if you look at it. Just modify as needed.

> On Mar 1, 2018, at 9:48 AM, Erik Kastman <notifications@github.com> wrote:
> 
> Hi @iankorf,
> 
> I'm trying to implement the AGAPE Yeast annotation pipeline in our lab, and am finding some inconsistencies. One that you may be able to help me with is a script called gff2zff.pl, used with a -sp <name> flag, from here:
> 
> https://github.com/yeastgenome/AGAPE/blob/9825c208853a696631c93fcfe6b041e16cf7db0f/prep_maker.sh#L20
> 
> It seems that script was distributed within SNAP (I also found a reference on biostars saying that script was "from the author", but I can't find it in any of the releases on gitlab or from the lab site. I found SNAP/gff3_to_zff.pl in this repo, but I don't think it tkaes the -sp flag, so I suspect it's not doing exactly what the AGAPE authors intended; I'm going to try it and see. In the meantime, would you mind pointing me in the right direction?
> 
> Thanks,
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

/***************************\
Ian Korf
Professor
UC Davis MCB & Genome Center
451 Health Sciences Drive
Davis CA 95616
ifkorf@ucdavis.edu
mobile: 530.574.0802
office: 530.754.4989
fax:    530.754.9658
\***************************/

**Comment by kastman** [comment]
Thanks for the prompt response, but do you have an old copy lying around in a dist download or email somewhere that I haven't found? There isn't one in any of the four dated distributions in http://korflab.ucdavis.edu/Software/ . 

Unless I'm missing something (which is possible) the `gff3_to_zff.pl` in the current repo is incomplete - I see it parsing the gff lines, but don't see it writing anything to stdout, either short or long form zff.

If the converter has already been written multiple times, I'm sure you can understand why I'm not super excited about writing it again, even if it is simple. I'm sure there are edge cases you've already fixed that I would have to fight with again.

**Comment by iankorf** [comment]
Can you send me a portion of your GFF? Despite GFF being a standard, it rarely ever is.

> On Mar 1, 2018, at 12:21 PM, Erik Kastman <notifications@github.com> wrote:
> 
> Thanks for the prompt response, but do you have an old copy lying around in a dist download or email somewhere that I haven't found? There isn't one in any of the four dated distributions in http://korflab.ucdavis.edu/Software/ .
> 
> Unless I'm missing something (which is possible) the gff3_to_zff.pl in the current repo is incomplete - I see it parsing the gff lines, but don't see it writing anything to stdout, either short or long form zff.
> 
> If the converter has already been written multiple times, I'm sure you can understand why I'm not super excited about writing it again, even if it is simple. I'm sure there are edge cases you've already fixed that I would have to fight with again.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

/***************************\
Ian Korf
Professor
UC Davis MCB & Genome Center
451 Health Sciences Drive
Davis CA 95616
ifkorf@ucdavis.edu
mobile: 530.574.0802
office: 530.754.4989
fax:    530.754.9658
\***************************/

**Comment by kastman** [comment]
Thanks @iankorf for looking at my gff and providing an appropriate parser so quickly. I’ll include it when I release my cleaned-up AGAPE pipeline.
