### ISSUE TITLE
Can't visualize the output in IGV

### ISSUE THREAD

**Issue by salvatierra8** [KorfLab/SNAP#19]
Greetings,

First, thanks for developing this tool. I have followed the tutorial to predict the genes of my assembly, I have succesfully obtained a gff3 file, and now I want to visualize the results along other files obtained through other tools. I'm using IGV  (didn't want to use Apollo because is not easy to understand all what I have to do to use it and seems to take a long time to set it up)and so far the other two tools I have used are loading without any problem (Augustus, and GeneMark). However for the case of SNAP output, I am getting the next message: 

Failed to parse line -1: Einit 3305 3403 + 17.721 0 0 1 WSC36_pilon-snap.1 Column 4 must contain a numeric value. For input string: "+" 

When comparing the gff files, I can conclude that the other two ouputs are pretty similar between them, but the snap output's columns are in different order. I tried to solve this by editing what seems to be causing problems. 

Now I am new to all of this bioinformatic stuff and I'm trying to avoid stuff with too much preparation and hours of reading just to understand only one action of a particular tool, so I tried doing this editing through libreoffice and then copying and pasting on an empty text editor file, and saving it as .gff file. Now there are error messages, but nothing to visualize, so either I can't do something simple as described above or I have not make all the proper changes. I would appreciate any help, or just assure me that it would work in an alternative to IGV (+sending your good vibes).

**Comment by iankorf** [comment]
SNAP doesn't output GFF3. There's a script in the repo that will convert SNAP format to GFF3. Your attempts to get SNAP output into IGV are sort of like filling your car's fuel tank with water. Anyone with an ounce of car knowledge would know the difference between gas and water. I understand that you don't care to learn bioinformatics stuff, but this is one of many problems you will face in the future. Either commit to learning or hand this off to someone else.
