### ISSUE TITLE
void uni.ann and uni.dna file

### ISSUE THREAD

**Issue by wuxiaopei0509** [KorfLab/SNAP#4]
When I use fathom genome.ann genome.dna -categorize 1000 to break up the sequences into fragments with one gene per sequence ,the output file is void ,what's the problem?Can you help with me?
Best regard！

**Comment by iankorf** [comment]
Hard to know without seeing the data going in.

**Comment by wuxiaopei0509** [comment]
Hi ,Professor
I didn't find the gff2zff script,so I used maker2zff to convert the gff file to zff file(the gff file derived from Arabidopsis thaliana standard annotation gff3),however when I use "fathom genome.ann genome.dna -categorize 1000 " command ,it produced null file.I didn't find any gff2zff script in the distribution. So can you provide the gff2zff script?

**Comment by iankorf** [comment]
I think there tend to be a lot of different versions of the gff standard and I've had to make custom scripts with each data source. Can you send me an example of the gff you're using?

**Comment by wuxiaopei0509** [comment]
HI,professor
The example gff3 file is uploaded as attachment.
Thank you very much!
Best







At 2019-11-20 03:27:06, "Ian Korf" <notifications@github.com> wrote:


I think there tend to be a lot of different versions of the gff standard and I've had to make custom scripts with each data source. Can you send me an example of the gff you're using?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的云附件
example.gff3 (30.01M, 2019年12月5日 18:43 到期)
下载
