### ISSUE TITLE
ZFF format, what type of feature to use? CDS is it enough?

### ISSUE THREAD

**Issue by Juke34** [KorfLab/SNAP#5]
On the common protocol to train snap is through MAKER annotation pipeline.
They provide a script called `maker2zff`. Looking at their script I realise that they use only the CDS coordinates to create Esngl,   Einit, Eterm,  Exon,  zff features.
What would be your recommendation to better train snap? 
Using CDS only is enough? Can we use exons only?
I checked `zoeFeature.h`, what about the other features? 

Would I get a better training if I provide a zff file with Intron,  UTR5,  UTR3,  Acceptor,  Donor,  	Start,   Stop, etc features?
Maybe most of them are compute automatically while training (i.e. start, stop, Acceptor,  Donor can be deduced by exon coordinates... )

`maker2zff` defines Esngl,   Einit, Eterm, Exon zff features  based on CDS gff features, would I get a better training if I define Esngl,  Einit, Eterm,  Exon based on Exon gff feature and add `Coding` zff feature to specify which part of the exon is coding?

**Comment by iankorf** [comment]
CDS. SNAP doesn't really model the non-coding parts.

**Comment by Juke34** [comment]
Does the separator field matter in the zff file? Should it be space or tabulation?

**Comment by iankorf** [comment]
I don't think it matters, but tab always looks better.

**Comment by Juke34** [comment]
A last remark, I think you don't mention in the readme that genome.dna and genome.ann must be sorted by sequence identifier in the same order.
I did a first try where my files were not sorted in the same order and got plenty of error messages.

**Comment by iankorf** [comment]
It processes them one at a time. Back when SNAP was first developed, there was no way you could all the chromosomes and annotation in at once.
